# Generated by Django 5.1.6 on 2025-03-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=10, unique=True, verbose_name='username'),
        ),
    ]
